from django.core.management.base import BaseCommand
from lojinha.models import Item

class Command(BaseCommand):
    """
    Comando para criar itens, pois ninguém merece digitar essa parada.
    """
    help = 'Create random items'

    def handle(self, *args, **kwargs):
        items = [
            {'title': 'Caneta Bic Azul', 'description': 'Caneta esferográfica azul', 'price': 1.50, 'stock': 30000, 'commission_rate': 5, 'image': 'products/bic_blue.jpg'},  # noqa: E501
            {'title': 'Caderno Tilibra - Três Porquinhos', 'description': 'Caderno universitário com 200 folhas', 'price': 20.00, 'stock': 15000, 'commission_rate': 10, 'image': 'products/tilibra_notebook.jpg'},  # noqa: E501
            {'title': 'Mouse Logitech MX Master 3S', 'description': 'Mouse óptico sem fio', 'price': 600.00, 'stock': 2000, 'commission_rate': 5, 'image': 'products/logitech_mouse.jpg'},  # noqa: E501
            {'title': 'Teclado Microsoft Wireless Desktop 850', 'description': 'Teclado sem fio', 'price': 120.00, 'stock': 1000, 'commission_rate': 2.0, 'image': 'products/microsoft_keyboard.jpg'},  # noqa: E501
            {'title': 'Galaxy S20 - Smartphone Samsung', 'description': 'Smartphone Samsung Galaxy S20', 'price': 3500.00, 'stock': 500, 'commission_rate': 8, 'image': 'products/samsung_galaxy.jpg'}, # noqa: E501
            {'title': 'Impressora Multifuncional Epson Ecotank L3210', 'description': 'Impressora jato de tinta colorida', 'price': 800.00, 'stock': 300, 'commission_rate': 8, 'image': 'products/epson_printer.jpg'}, # noqa: E501
            {'title': 'Lápis de Cor Faber-Castell', 'description': 'Jogo com 36 lápis de cor', 'price': 35.00, 'stock': 1200, 'commission_rate': 5, 'image': 'products/faber_castell_colored_pencils.jpg'}, # noqa: E501
            {'title': 'Agenda 2023', 'description': 'Agenda semanal para o ano de 2023', 'price': 25.00, 'stock': 3000, 'commission_rate': 8, 'image': 'products/2023_agenda.jpg'}, # noqa: E501
            {'title': 'Headset Gamer HyperX Cloud II', 'description': 'Fone de ouvido gamer com som surround', 'price': 300.00, 'stock': 1500, 'commission_rate': 7, 'image': 'products/hyperx_headset.jpg'}, # noqa: E501
            {'title': 'Cadeira Ergonômica', 'description': 'Cadeira giratória com apoio lombar ajustável', 'price': 450.00, 'stock': 200, 'commission_rate': 10, 'image': 'products/ergonomic_chair.jpg'}, # noqa: E501
            {'title': 'Monitor Dell Ultrasharp', 'description': 'Monitor LED IPS de 24 polegadas', 'price': 250.00, 'stock': 300, 'commission_rate': 6, 'image': 'products/dell_monitor.jpg'},  # noqa: E501
            {'title': 'HD Externo Seagate', 'description': 'HD externo portátil de 1TB', 'price': 80.00, 'stock': 800, 'commission_rate': 3, 'image': 'products/seagate_external_hd.jpg'}, # noqa: E501
            {'title': 'Calculadora Científica Casio', 'description': 'Calculadora científica com visor LCD', 'price': 40.00, 'stock': 7500, 'commission_rate': 5, 'image': 'products/casio_calculator.jpg'}, # noqa: E501
            {'title': 'Caneta Esferográfica Gel Uni-ball', 'description': 'Caneta gel com tinta de qualidade', 'price': 2.50, 'stock': 25000, 'commission_rate': 3, 'image': 'products/uniball_pen.jpg'}, # noqa: E501
            {'title': 'Pasta de Arquivos', 'description': 'Pasta com elástico para organização de documentos', 'price': 5.00, 'stock': 2000, 'commission_rate': 2, 'image': 'products/file_folder.jpg'}, # noqa: E501
            {'title': 'Notebook HP Pavilion', 'description': 'Notebook com processador Intel Core i5 e 8GB de RAM', 'price': 1000.00, 'stock': 500, 'commission_rate': 8, 'image': 'products/hp_notebook.jpg'}, # noqa: E501
            {'title': 'Régua Transparente', 'description': 'Régua de 30 cm em acrílico transparente', 'price': 2.00, 'stock': 12000, 'commission_rate': 1, 'image': 'products/transparent_ruler.jpg'}, # noqa: E501
            {'title': 'Papel A4 75g/m²', 'description': 'Pacote com 500 folhas de papel tamanho A4', 'price': 10.00, 'stock': 10000, 'commission_rate': 2, 'image': 'products/a4_paper.jpg'}, # noqa: E501
            {'title': 'Giz de Cera Crayola', 'description': 'Caixa com 24 cores de giz de cera', 'price': 8.00, 'stock': 3000, 'commission_rate': 4, 'image': 'products/crayola_crayons.jpg'}, # noqa: E501
            {'title': 'Grampeador Profissional', 'description': 'Grampeador de alta capacidade para uso profissional', 'price': 15.00, 'stock': 10000, 'commission_rate': 3, 'image': 'products/professional_stapler.jpg'}, # noqa: E501
            {'title': 'Mochila SwissGear', 'description': 'Mochila resistente com compartimento para laptop', 'price': 50.00, 'stock': 2000, 'commission_rate': 6, 'image': 'products/swissgear_backpack.jpg'}, # noqa: E501
            {'title': 'Caneta Apagável Pilot Frixion', 'description': 'Caneta gel apagável com ponta fina', 'price': 3.50, 'stock': 15000, 'commission_rate': 2, 'image': 'products/pilot_frixion_pen.jpg'}, # noqa: E501
            {'title': 'Mousepad Gaming', 'description': 'Mousepad de alta precisão para jogos', 'price': 10.00, 'stock': 550, 'commission_rate': 2, 'image': 'products/gaming_mousepad.jpg'}, # noqa: E501
            {'title': 'Caixa de Papelão', 'description': 'Caixa de papelão resistente para armazenamento', 'price': 3.00, 'stock': 10000, 'commission_rate': 1, 'image': 'products/cardboard_box.jpg'}, # noqa: E501
            {'title': 'Agenda Planner', 'description': 'Agenda planner semanal com páginas personalizáveis', 'price': 25.00, 'stock': 12000, 'commission_rate': 5, 'image': 'products/planner_agenda.jpg'}, # noqa: E501
            {'title': 'Tesoura de Precisão', 'description': 'Tesoura de ponta fina para trabalhos detalhados', 'price': 8.50, 'stock': 3000, 'commission_rate': 3, 'image': 'products/precision_scissors.jpg'}, # noqa: E501
            {'title': 'Mouse sem Fio', 'description': 'Mouse sem fio para maior liberdade de movimento', 'price': 20.00, 'stock': 5000, 'commission_rate': 4, 'image': 'products/wireless_mouse.jpg'}, # noqa: E501
            {'title': 'Calculadora de Mesa', 'description': 'Calculadora de mesa com display de 12 dígitos', 'price': 12.00, 'stock': 10000, 'commission_rate': 2, 'image': 'products/desktop_calculator.jpg'}, # noqa: E501
            {'title': 'Pen Drive USB 3.0', 'description': 'Pen drive com capacidade de 32GB e velocidade USB 3.0', 'price': 15.00, 'stock': 2500, 'commission_rate': 3, 'image': 'products/usb_drive.jpg'}, # noqa: E501
            {'title': 'Caixa Organizadora', 'description': 'Caixa organizadora de plástico com divisórias', 'price': 10.00, 'stock': 3000, 'commission_rate': 2, 'image': 'products/organizer_box.jpg'}, # noqa: E501
            {'title': 'Post-it Notes', 'description': 'Bloco de notas adesivas coloridas', 'price': 3.00, 'stock': 5000, 'commission_rate': 2, 'image': 'products/post_it_notes.jpg'}, # noqa: E501
            {'title': 'Caneta Marca-texto Stabilo', 'description': 'Conjunto de 4 canetas marca-texto neon', 'price': 6.50, 'stock': 12000, 'commission_rate': 3, 'image': 'products/stabilo_highlighters.jpg'}, # noqa: E501
            {'title': 'Webcam Logitech C920', 'description': 'Webcam HD com microfone integrado', 'price': 60.00, 'stock': 100, 'commission_rate': 5, 'image': 'products/logitech_webcam.jpg'}, # noqa: E501
            {'title': 'Bloco de Notas Pautado', 'description': 'Bloco de notas com linhas para anotações', 'price': 2.50, 'stock': 500, 'commission_rate': 1, 'image': 'products/ruled_notepad.jpg'}, # noqa: E501
            {'title': 'Carregador Portátil', 'description': 'Carregador portátil com capacidade de 10.000mAh', 'price': 25.00, 'stock': 1500, 'commission_rate': 4, 'image': 'products/portable_charger.jpg'}, # noqa: E501
            {'title': 'Lanterna LED', 'description': 'Lanterna portátil com luz LED', 'price': 8.00, 'stock': 3000, 'commission_rate': 2, 'image': 'products/led_flashlight.jpg'}, # noqa: E501
            {'title': 'Gravador de Voz Digital', 'description': 'Gravador de voz portátil com capacidade de 8GB', 'price': 40.00, 'stock': 5000, 'commission_rate': 5, 'image': 'products/digital_voice_recorder.jpg'}, # noqa: E501
            {'title': 'Caneta Esferográfica Parker', 'description': 'Caneta esferográfica de luxo da marca Parker', 'price': 30.00, 'stock': 8500, 'commission_rate': 4, 'image': 'products/parker_ballpoint_pen.jpg'}, # noqa: E501
            {'title': 'Monitor Curvo Samsung', 'description': 'Monitor curvo LED de 27 polegadas', 'price': 300.00, 'stock': 500, 'commission_rate': 6, 'image': 'products/samsung_curved_monitor.jpg'}, # noqa: E501
            {'title': 'Caixa de Clips Coloridos', 'description': 'Caixa com 100 clips coloridos', 'price': 5.00, 'stock': 12000, 'commission_rate': 2, 'image': 'products/colored_paper_clips.jpg'}, # noqa: E501
            {'title': 'Hub USB', 'description': 'Hub USB com 4 portas para expansão de conectividade', 'price': 15.00, 'stock': 30000, 'commission_rate': 3, 'image': 'products/usb_hub.jpg'}, # noqa: E501
            {'title': 'Fita Adesiva Transparente', 'description': 'Rolo de fita adesiva transparente de alta resistência', 'price': 2.00, 'stock': 5000, 'commission_rate': 1, 'image': 'products/transparent_tape.jpg'}, # noqa: E501
            {'title': 'Agenda Executiva', 'description': 'Agenda com capa de couro para uso executivo', 'price': 35.00, 'stock': 15000, 'commission_rate': 5, 'image': 'products/executive_agenda.jpg'}, # noqa: E501
            {'title': 'Caneta Rollerball', 'description': 'Caneta rollerball com tinta de gel suave', 'price': 4.50, 'stock': 20000, 'commission_rate': 3, 'image': 'products/rollerball_pen.jpg'}, # noqa: E501
            {'title': 'Mouse Ergonômico', 'description': 'Mouse ergonômico com design confortável', 'price': 25.00, 'stock': 3500, 'commission_rate': 4, 'image': 'products/ergonomic_mouse.jpg'}, # noqa: E501
            {'title': 'Etiquetas Adesivas', 'description': 'Pacote com 500 etiquetas adesivas variadas', 'price': 3.00, 'stock': 12000, 'commission_rate': 1, 'image': 'products/adhesive_labels.jpg'}, # noqa: E501
            {'title': 'Teclado Mecânico', 'description': 'Teclado mecânico retroiluminado para jogos', 'price': 80.00, 'stock': 1000, 'commission_rate': 7, 'image': 'products/mechanical_keyboard.jpg'}, # noqa: E501
            {'title': 'Bateria Recarregável', 'description': 'Bateria recarregável AA de longa duração', 'price': 10.00, 'stock': 5000, 'commission_rate': 2, 'image': 'products/rechargeable_battery.jpg'}, # noqa: E501
            {'title': 'Bloco de Notas Autoadesivas', 'description': 'Bloco de notas autoadesivas em diferentes cores e tamanhos', 'price': 3.50, 'stock': 12000, 'commission_rate': 2, 'image': 'products/self_stick_notes.jpg'}, # noqa: E501
            {'title': 'Caneta Tinteiro', 'description': 'Caneta tinteiro de alta qualidade para escrita suave', 'price': 20.00, 'stock': 5000, 'commission_rate': 4, 'image': 'products/fountain_pen.jpg'}, # noqa: E501
            {'title': 'Monitor Ultrawide LG', 'description': 'Monitor ultrawide de 34 polegadas com resolução QHD', 'price': 500.00, 'stock': 550, 'commission_rate': 8, 'image': 'products/lg_ultrawide_monitor.jpg'}, # noqa: E501
            {'title': 'Grampos de Papel', 'description': 'Caixa com 1000 grampos de papel metálicos', 'price': 2.00, 'stock': 5000, 'commission_rate': 1, 'image': 'products/paper_clips.jpg'}, # noqa: E501
            {'title': 'Adaptador USB-C', 'description': 'Adaptador USB-C para conexões versáteis', 'price': 8.00, 'stock': 8000, 'commission_rate': 2, 'image': 'products/usb_c_adapter.jpg'}, # noqa: E501
            {'title': 'Fita Corretiva', 'description': 'Rolo de fita corretiva para correção de texto', 'price': 2.50, 'stock': 13000, 'commission_rate': 1, 'image': 'products/correction_tape.jpg'}, # noqa: E501
            {'title': 'Organizador de Cabos', 'description': 'Organizador de cabos com clips e suportes', 'price': 6.00, 'stock': 8000, 'commission_rate': 7, 'image': 'products/cable_organizer.jpg'}, # noqa: E501
            {'title': 'Lápis Mecânico', 'description': 'Lápis mecânico com ponta fina e borracha embutida', 'price': 4.50, 'stock': 3000, 'commission_rate': 2, 'image': 'products/mechanical_pencil.jpg'}, # noqa: E501
            {'title': 'Máquina de Etiquetas', 'description': 'Máquina manual para criar etiquetas personalizadas', 'price': 30.00, 'stock': 5000, 'commission_rate': 5, 'image': 'products/label_maker.jpg'}, # noqa: E501
            {'title': 'Monitor de Frequência Cardíaca', 'description': 'Monitor de frequência cardíaca para atividades físicas', 'price': 45.00, 'stock': 1000, 'commission_rate': 5, 'image': 'products/heart_rate_monitor.jpg'}, # noqa: E501
            {'title': 'Organizador de Escritório', 'description': 'Organizador de mesa para canetas, clips e outros itens', 'price': 12.00, 'stock': 1500, 'commission_rate': 3, 'image': 'products/desktop_organizer.jpg'}, # noqa: E501
            {'title': 'Porta-Retratos', 'description': 'Porta-retratos de mesa para exibir fotos', 'price': 8.00, 'stock': 1200, 'commission_rate': 2, 'image': 'products/photo_frame.jpg'}, # noqa: E501
            {'title': 'Dell XPS 15', 'description': 'Notebook de alto desempenho com tela de 15 polegadas', 'price': 1999.00, 'stock': 200, 'commission_rate': 2, 'image': 'products/dell_xps15.jpg'}, # noqa: E501
            {'title': 'MacBook Pro 13', 'description': 'Notebook premium da Apple com tela de 13 polegadas', 'price': 1799.00, 'stock': 500, 'commission_rate': 8, 'image': 'products/macbook_pro13.jpg'}, # noqa: E501
            {'title': 'HP Spectre x360', 'description': 'Notebook conversível com tela sensível ao toque', 'price': 1299.00, 'stock': 1500, 'commission_rate': 2, 'image': 'products/hp_spectre_x360.jpg'}, # noqa: E501
            {'title': 'ASUS ROG Zephyrus G14', 'description': 'Notebook gamer com poderoso processador AMD Ryzen', 'price': 1499.00, 'stock': 1200, 'commission_rate': 2, 'image': 'products/asus_rog_zephyrus.jpg'}, # noqa: E501
            {'title': 'Acer Swift 3', 'description': 'Notebook fino e leve com ótimo custo-benefício', 'price': 899.00, 'stock': 2000, 'commission_rate': 6, 'image': 'products/acer_swift3.jpg'}, # noqa: E501
            {'title': 'Microsoft Surface Laptop 4', 'description': 'Notebook elegante e portátil com tela sensível ao toque', 'price': 1399.00, 'stock': 1000, 'commission_rate': 2, 'image': 'products/microsoft_surface_laptop4.jpg'}, # noqa: E501
            {'title': 'Dell Inspiron 15', 'description': 'Notebook versátil com tela de 15 polegadas e configurações personalizáveis', 'price': 999.00, 'stock': 1005, 'commission_rate': 2, 'image': 'products/dell_inspiron15.jpg'}, # noqa: E501
            {'title': 'Lenovo Yoga C940', 'description': 'Notebook conversível com tela 2 em 1 e alto desempenho', 'price': 1299.00, 'stock': 800, 'commission_rate': 2, 'image': 'products/lenovo_yoga_c940.jpg'}, # noqa: E501
            {'title': 'HP Envy x360', 'description': 'Notebook conversível com tela sensível ao toque e desempenho sólido', 'price': 1099.00, 'stock': 1600, 'commission_rate': 3, 'image': 'products/hp_envy_x360.jpg'}, # noqa: E501
            {'title': 'ASUS ZenBook 14', 'description': 'Notebook ultraleve e compacto com excelente duração de bateria', 'price': 1199.00, 'stock': 1800, 'commission_rate': 2, 'image': 'products/asus_zenbook14.jpg'}, # noqa: E501
            {'title': 'Acer Predator Helios 300', 'description': 'Notebook gamer com poderoso desempenho e placa gráfica dedicada', 'price': 1599.00, 'stock': 5000, 'commission_rate': 2, 'image': 'products/acer_predator_helios300.jpg'}, # noqa: E501
            {'title': 'iPhone 13 Pro', 'description': 'Celular premium da Apple com câmeras avançadas e desempenho poderoso', 'price': 1099.00, 'stock': 1000, 'commission_rate': 10, 'image': 'products/iphone_13_pro.jpg'}, # noqa: E501
            {'title': 'Samsung Galaxy S21 Ultra', 'description': 'Celular flagship da Samsung com tela grande e recursos de câmera profissional', 'price': 1199.00, 'stock':1800, 'commission_rate': 2, 'image': 'products/galaxy_s21_ultra.jpg'}, # noqa: E501
            {'title': 'Google Pixel 6', 'description': 'Celular com câmera excepcional e integração aprimorada com os serviços do Google', 'price': 799.00, 'stock': 1200, 'commission_rate': 2, 'image': 'products/google_pixel_6.jpg'}, # noqa: E501
            {'title': 'OnePlus 9 Pro', 'description': 'Celular com tela fluida e desempenho de alto nível', 'price': 999.00, 'stock': 1500, 'commission_rate': 2, 'image': 'products/oneplus_9_pro.jpg'}, # noqa: E501
            {'title': 'Xiaomi Mi 11', 'description': 'Celular com processador poderoso e excelente qualidade de tela', 'price': 699.00, 'stock': 2000, 'commission_rate': 6, 'image': 'products/xiaomi_mi_11.jpg'}, # noqa: E501
            {'title': 'Pacote de Papel Navigator', 'description': 'Pacote com 500 folhas de papel Navigator A4', 'price': 20.00, 'stock': 12000, 'commission_rate': 2, 'image': 'products/navigator_paper.jpg'}, # noqa: E501
            {'title': 'Pacote de Papel HP', 'description': 'Pacote com 250 folhas de papel HP A4', 'price': 12.00, 'stock': 18000, 'commission_rate': 2, 'image': 'products/hp_paper.jpg'}, # noqa: E501
            {'title': 'Pacote de Papel Double A', 'description': 'Pacote com 500 folhas de papel Double A A4', 'price': 18.00, 'stock': 14000, 'commission_rate': 5, 'image': 'products/double_a_paper.jpg'}, # noqa: E501
            {'title': 'Monitor LG 27GL850', 'description': 'Monitor IPS de 27 polegadas com resolução QHD e taxa de atualização de 144Hz', 'price': 499.00, 'stock': 1000, 'commission_rate': 2, 'image': 'products/lg_27gl850.jpg'}, # noqa: E501
            {'title': 'Monitor Dell Ultrasharp U2419H', 'description': 'Monitor LED IPS de 24 polegadas com resolução Full HD e amplo ângulo de visão', 'price': 249.00, 'stock': 1500, 'commission_rate': 2, 'image': 'products/dell_u2419h.jpg'}, # noqa: E501
            {'title': 'Monitor ASUS ROG Swift PG279Q', 'description': 'Monitor gaming de 27 polegadas com resolução WQHD e taxa de atualização de 165Hz', 'price': 699.00, 'stock': 2800, 'commission_rate': 4, 'image': 'products/asus_pg279q.jpg'}, # noqa: E501
            {'title': 'Monitor Samsung Odyssey G7', 'description': 'Monitor curvo QLED de 32 polegadas com resolução 4K e taxa de atualização de 240Hz', 'price': 1299.00, 'stock': 5000, 'commission_rate': 3, 'image': 'products/samsung_odyssey_g7.jpg'}, # noqa: E501
            {'title': 'Monitor HP Pavilion 22cwa', 'description': 'Monitor LED IPS de 21,5 polegadas com resolução Full HD e design ultrafino', 'price': 129.00, 'stock': 2000, 'commission_rate': 8, 'image': 'products/hp_pavilion_22cwa.jpg'}, # noqa: E501
            {'title': 'Monitor BenQ PD3200U', 'description': 'Monitor profissional de 32 polegadas com resolução 4K e tecnologia IPS', 'price': 899.00, 'stock': 1000, 'commission_rate': 2, 'image': 'products/benq_pd3200u.jpg'}, # noqa: E501
            {'title': 'Impressora Epson EcoTank ET-4760', 'description': 'Impressora multifuncional com sistema de tanque de tinta de alto rendimento', 'price': 399.00, 'stock': 2000, 'commission_rate': 2, 'image': 'products/epson_et4760.jpg'}, # noqa: E501
            {'title': 'Impressora HP LaserJet Pro M283fdw', 'description': 'Impressora laser multifuncional com conectividade sem fio e impressão duplex', 'price': 399.00, 'stock': 1800, 'commission_rate': 2, 'image': 'products/hp_laserjet_m283fdw.jpg'}, # noqa: E501
            {'title': 'Impressora Canon PIXMA iP8720', 'description': 'Impressora jato de tinta para impressões de alta qualidade e tamanhos até 13x19 polegadas', 'price': 249.00, 'stock': 2500, 'commission_rate': 2, 'image': 'products/canon_pixma_ip8720.jpg'}, # noqa: E501
            {'title': 'Impressora Brother HL-L2370DW', 'description': 'Impressora laser monocromática com impressão duplex e conectividade sem fio', 'price': 179.00, 'stock': 2200, 'commission_rate': 6, 'image': 'products/brother_hll2370dw.jpg'}, # noqa: E501
            {'title': 'Impressora Epson WorkForce Pro WF-4740', 'description': 'Impressora jato de tinta multifuncional com impressão rápida e eficiente', 'price': 299.00, 'stock': 6000, 'commission_rate': 2, 'image': 'products/epson_wf4740.jpg'}, # noqa: E501
            {'title': 'Impressora HP OfficeJet Pro 9025', 'description': 'Impressora jato de tinta multifuncional com alta velocidade de impressão e recursos avançados', 'price': 329.00, 'stock': 1000, 'commission_rate': 2, 'image': 'products/hp_officejet_pro9025.jpg'}, # noqa: E501
            {'title': 'Cartucho de Tinta HP 63', 'description': 'Cartucho de tinta original HP 63 para impressoras HP', 'price': 25.00, 'stock': 5000, 'commission_rate': 4, 'image': 'products/hp_63_ink.jpg'}, # noqa: E501
            {'title': 'Cartucho de Tinta Epson 288', 'description': 'Cartucho de tinta original Epson 288 para impressoras Epson', 'price': 30.00, 'stock': 4000, 'commission_rate': 2, 'image': 'products/epson_288_ink.jpg'}, # noqa: E501
            {'title': 'Cartucho de Tinta Canon CLI-271', 'description': 'Cartucho de tinta original Canon CLI-271 para impressoras Canon', 'price': 20.00, 'stock': 6000, 'commission_rate': 3, 'image': 'products/canon_cli271_ink.jpg'}, # noqa: E501
            {'title': 'Cartucho de Tinta Brother LC103', 'description': 'Cartucho de tinta original Brother LC103 para impressoras Brother', 'price': 15.00, 'stock': 3000, 'commission_rate': 3, 'image': 'products/brother_lc103_ink.jpg'}, # noqa: E501
            {'title': 'Cartucho de Tinta Lexmark 100', 'description': 'Cartucho de tinta original Lexmark 100 para impressoras Lexmark', 'price': 18.00, 'stock': 2000, 'commission_rate': 2, 'image': 'products/lexmark_100_ink.jpg'}, # noqa: E501
            {'title': 'Cartucho de Tinta Xerox Phaser 6022', 'description': 'Cartucho de tinta original Xerox Phaser 6022 para impressoras Xerox', 'price': 22.00, 'stock': 3500, 'commission_rate': 2, 'image': 'products/xerox_phaser_6022_ink.jpg'}, # noqa: E501
            {'title': 'Toner HP 85A', 'description': 'Toner original HP 85A para impressoras HP LaserJet', 'price': 50.00, 'stock': 2550, 'commission_rate': 8, 'image': 'products/hp_85a_toner.jpg'}, # noqa: E501
            {'title': 'Toner Brother TN450', 'description': 'Toner original Brother TN450 para impressoras Brother', 'price': 40.00, 'stock': 4000, 'commission_rate': 2, 'image': 'products/brother_tn450_toner.jpg'}, # noqa: E501
            {'title': 'Toner Samsung MLT-D111S', 'description': 'Toner original Samsung MLT-D111S para impressoras Samsung', 'price': 35.00, 'stock': 6000, 'commission_rate': 6, 'image': 'products/samsung_mlt_d111s_toner.jpg'}, # noqa: E501
            {'title': 'Toner Canon 137', 'description': 'Toner original Canon 137 para impressoras Canon imageCLASS', 'price': 45.00, 'stock': 3000, 'commission_rate': 2, 'image': 'products/canon_137_toner.jpg'}, # noqa: E501
            {'title': 'Toner Lexmark E260A11L', 'description': 'Toner original Lexmark E260A11L para impressoras Lexmark E260', 'price': 55.00, 'stock': 2000, 'commission_rate': 5, 'image': 'products/lexmark_e260a11l_toner.jpg'}, # noqa: E501
            {'title': 'Toner Xerox 106R02777', 'description': 'Toner original Xerox 106R02777 para impressoras Xerox Phaser', 'price': 60.00, 'stock': 3500, 'commission_rate': 2, 'image': 'products/xerox_106r02777_toner.jpg'}, # noqa: E501
            {'title': 'Caneta Uni-ball Jetstream', 'description': 'Caneta esferográfica Uni-ball Jetstream', 'price': 2.50, 'stock': 8000, 'commission_rate': 5, 'image': 'products/uniball_jetstream.jpg'},  # noqa: E501
            {'title': 'Caneta Pilot G2', 'description': 'Caneta gel Pilot G2', 'price': 2.00, 'stock': 6000, 'commission_rate': 4, 'image': 'products/pilot_g2.jpg'}, # noqa: E501
            {'title': 'Caneta Faber-Castell Grip 2001', 'description': 'Caneta esferográfica Faber-Castell Grip 2001', 'price': 3.00, 'stock': 5000, 'commission_rate': 6, 'image': 'products/faber_castell_grip2001.jpg'}, # noqa: E501
            {'title': 'Caneta Paper Mate InkJoy', 'description': 'Caneta esferográfica Paper Mate InkJoy', 'price': 1.80, 'stock': 7000, 'commission_rate': 4, 'image': 'products/papermate_inkjoy.jpg'}, # noqa: E501
            {'title': 'Caneta Stabilo Point 88', 'description': 'Caneta de ponta fina Stabilo Point 88', 'price': 1.90, 'stock': 4000, 'commission_rate': 4, 'image': 'products/stabilo_point88.jpg'}, # noqa: E501
            {'title': 'Caneta Pentel EnerGel', 'description': 'Caneta gel Pentel EnerGel', 'price': 2.30, 'stock': 5500, 'commission_rate': 5, 'image': 'products/pentel_energel.jpg'}, # noqa: E501
            {'title': 'Caneta Schneider Slider XB', 'description': 'Caneta esferográfica Schneider Slider XB', 'price': 2.10, 'stock': 3500, 'commission_rate': 4, 'image': 'products/schneider_slider.jpg'}, # noqa: E501
            {'title': 'Caneta Zebra Sarasa', 'description': 'Caneta gel Zebra Sarasa', 'price': 1.80, 'stock': 6000, 'commission_rate': 4, 'image': 'products/zebra_sarasa.jpg'}, # noqa: E501
            {'title': 'Caneta Pilot V5', 'description': 'Caneta rollerball Pilot V5', 'price': 2.20, 'stock': 4500, 'commission_rate': 5, 'image': 'products/pilot_v5.jpg'}, # noqa: E501
            {'title': 'Lapiseira Pentel Graphgear 500', 'description': 'Lapiseira Pentel Graphgear 500 com ponta 0.5mm', 'price': 5.50, 'stock': 2000, 'commission_rate': 6, 'image': 'products/pentel_graphgear500.jpg'}, # noqa: E501
            {'title': 'Lapiseira Uni Mechanical Pencil', 'description': 'Lapiseira Uni Mechanical Pencil com ponta 0.7mm', 'price': 3.80, 'stock': 3000, 'commission_rate': 5, 'image': 'products/uni_mechanical_pencil.jpg'}, # noqa: E501
            {'title': 'Lapiseira Faber-Castell TK-Fine Vario', 'description': 'Lapiseira Faber-Castell TK-Fine Vario com ponta ajustável', 'price': 6.20, 'stock': 2500, 'commission_rate': 6, 'image': 'products/faber_castell_tkfinevario.jpg'}, # noqa: E501
            {'title': 'Lapiseira Staedtler 925 25', 'description': 'Lapiseira Staedtler 925 25 com ponta 0.5mm', 'price': 4.50, 'stock': 2800, 'commission_rate': 5, 'image': 'products/staedtler_92525.jpg'}, # noqa: E501
            {'title': 'Lapiseira Pilot Automac', 'description': 'Lapiseira Pilot Automac com ponta 0.5mm', 'price': 7.00, 'stock': 1800, 'commission_rate': 7, 'image': 'products/pilot_automac.jpg'}, # noqa: E501
            {'title': 'Lápis Faber-Castell HB', 'description': 'Lápis Faber-Castell com graduação HB', 'price': 0.50, 'stock': 5000, 'commission_rate': 3, 'image': 'products/faber_castell_hb.jpg'}, # noqa: E501
            {'title': 'Lápis Staedtler Mars Lumograph', 'description': 'Lápis Staedtler Mars Lumograph com graduação 2B', 'price': 0.80, 'stock': 4000, 'commission_rate': 4, 'image': 'products/staedtler_mars_lumograph.jpg'}, # noqa: E501
            {'title': 'Lápis Tilibra 48 Cores', 'description': 'Lápis de cor Tilibra com 48 cores', 'price': 5.50, 'stock': 2000, 'commission_rate': 6, 'image': 'products/tilibra_48_cores.jpg'}, # noqa: E501
            {'title': 'Lápis de Cor Faber-Castell', 'description': 'Lápis de cor Faber-Castell com 24 cores', 'price': 8.00, 'stock': 1500, 'commission_rate': 7, 'image': 'products/faber_castell_lapis_de_cor.jpg'}, # noqa: E501
            {'title': 'Lápis Staedtler Noris', 'description': 'Lápis Staedtler Noris com graduação 2H', 'price': 0.60, 'stock': 4500, 'commission_rate': 4, 'image': 'products/staedtler_noris.jpg'}, # noqa: E501
            {'title': 'Borracha Staedtler Mars Plastic', 'description': 'Borracha Staedtler Mars Plastic de alta qualidade', 'price': 1.20, 'stock': 3000, 'commission_rate': 4, 'image': 'products/staedtler_mars_plastic.jpg'}, # noqa: E501
            {'title': 'Borracha Faber-Castell Dust-Free', 'description': 'Borracha Faber-Castell Dust-Free livre de resíduos', 'price': 1.50, 'stock': 2500, 'commission_rate': 4, 'image': 'products/faber_castell_dustfree.jpg'}, # noqa: E501
            {'title': 'Borracha Milan 430', 'description': 'Borracha Milan 430 de alta eficiência', 'price': 1.00, 'stock': 3500, 'commission_rate': 3, 'image': 'products/milan_430.jpg'}, # noqa: E501
            {'title': 'Borracha Tombow Mono', 'description': 'Borracha Tombow Mono de apagamento preciso', 'price': 2.00, 'stock': 2000, 'commission_rate': 5, 'image': 'products/tombow_mono.jpg'}, # noqa: E501
            {'title': 'Borracha Pentel Hi-Polymer', 'description': 'Borracha Pentel Hi-Polymer resistente e macia', 'price': 1.30, 'stock': 2800, 'commission_rate': 3, 'image': 'products/pentel_hipolymer.jpg'}, # noqa: E501
            {'title': 'Grampeador Swingline 747', 'description': 'Grampeador Swingline 747 de alta resistência', 'price': 15.00, 'stock': 1000, 'commission_rate': 6, 'image': 'products/swingline_747_stapler.jpg'}, # noqa: E501
            {'title': 'Grampeador Rapid K1', 'description': 'Grampeador Rapid K1 com capacidade para até 50 folhas', 'price': 12.50, 'stock': 800, 'commission_rate': 5, 'image': 'products/rapid_k1_stapler.jpg'}, # noqa: E501
            {'title': 'Grampeador Bostitch B8', 'description': 'Grampeador Bostitch B8 com mecanismo anti-emperramento', 'price': 18.00, 'stock': 1200, 'commission_rate': 6, 'image': 'products/bostitch_b8_stapler.jpg'}, # noqa: E501
            {'title': 'Caderno Universitário', 'description': 'Caderno universitário com capa dura e 200 folhas', 'price': 10.00, 'stock': 500, 'commission_rate': 4, 'image': 'products/caderno_universitario.jpg'}, # noqa: E501
            {'title': 'Caderno de Desenho', 'description': 'Caderno de desenho com folhas em branco e capa flexível', 'price': 8.50, 'stock': 300, 'commission_rate': 3, 'image': 'products/caderno_desenho.jpg'}, # noqa: E501
            {'title': 'Caderno de Anotações', 'description': 'Caderno compacto para anotações e ideias', 'price': 6.50, 'stock': 400, 'commission_rate': 2, 'image': 'products/caderno_anotacoes.jpg'}, # noqa: E501
            {'title': 'Caderno de Pauta', 'description': 'Caderno com folhas pautadas e espiral', 'price': 7.00, 'stock': 350, 'commission_rate': 3, 'image': 'products/caderno_pauta.jpg'}, # noqa: E501
            {'title': 'Caderno de Caligrafia', 'description': 'Caderno com guias para prática de caligrafia', 'price': 9.00, 'stock': 250, 'commission_rate': 4, 'image': 'products/caderno_caligrafia.jpg'}, # noqa: E501
            {'title': 'Caderno Universitário Capa Dura', 'description': 'Caderno universitário com capa dura e 300 folhas', 'price': 12.50, 'stock': 400, 'commission_rate': 5, 'image': 'products/caderno_universitario_capa_dura.jpg'}, # noqa: E501
            {'title': 'Caderno Universitário com Divisórias', 'description': 'Caderno universitário com capa flexível, 200 folhas e divisórias', 'price': 11.00, 'stock': 350, 'commission_rate': 4, 'image': 'products/caderno_universitario_divisorias.jpg'}, # noqa: E501
            {'title': 'Caderno Universitário Espiral Colorido', 'description': 'Caderno universitário com capa dura, espiral colorido e 240 folhas', 'price': 13.50, 'stock': 300, 'commission_rate': 5, 'image': 'products/caderno_universitario_espiral_colorido.jpg'}, # noqa: E501
            {'title': 'Caderno Universitário com Bolso', 'description': 'Caderno universitário com capa flexível, bolso interno e 150 folhas', 'price': 9.50, 'stock': 450, 'commission_rate': 4, 'image': 'products/caderno_universitario_bolso.jpg'}, # noqa: E501
            {'title': 'Caderno Universitário Personalizado', 'description': 'Caderno universitário personalizado com nome e 200 folhas', 'price': 14.00, 'stock': 250, 'commission_rate': 6, 'image': 'products/caderno_universitario_personalizado.jpg'}, # noqa: E501
            {'title': 'Pen Drive Kingston DataTraveler 16GB', 'description': 'Pen Drive Kingston com capacidade de 16GB', 'price': 9.99, 'stock': 1000, 'commission_rate': 4, 'image': 'products/kingston_datatraveler_16gb.jpg'}, # noqa: E501
            {'title': 'Pen Drive SanDisk Ultra 32GB', 'description': 'Pen Drive SanDisk Ultra com capacidade de 32GB', 'price': 14.99, 'stock': 1080, 'commission_rate': 5, 'image': 'products/sandisk_ultra_32gb.jpg'}, # noqa: E501
            {'title': 'Pen Drive HP v236w 64GB', 'description': 'Pen Drive HP com capacidade de 64GB', 'price': 24.99, 'stock': 550, 'commission_rate': 6, 'image': 'products/hp_v236w_64gb.jpg'}, # noqa: E501
            {'title': 'Pen Drive Toshiba TransMemory 128GB', 'description': 'Pen Drive Toshiba com capacidade de 128GB', 'price': 39.99, 'stock': 530, 'commission_rate': 7, 'image': 'products/toshiba_transmemory_128gb.jpg'}, # noqa: E501
            {'title': 'Pen Drive Samsung BAR Plus 256GB', 'description': 'Pen Drive Samsung com capacidade de 256GB', 'price': 59.99, 'stock': 520, 'commission_rate': 8, 'image': 'products/samsung_bar_plus_256gb.jpg'}, # noqa: E501
            {'title': 'Jogo: The Witcher 3: Wild Hunt', 'description': 'RPG de ação ambientado em um mundo aberto', 'price': 49.99, 'stock': 850, 'commission_rate': 10, 'image': 'products/witcher_3.jpg'}, # noqa: E501
            {'title': 'Jogo: Overwatch', 'description': 'Jogo de tiro em equipe com heróis', 'price': 39.99, 'stock': 530, 'commission_rate': 8, 'image': 'products/overwatch.jpg'}, # noqa: E501
            {'title': 'Jogo: Minecraft', 'description': 'Jogo sandbox de construção e aventura', 'price': 24.99, 'stock': 1580, 'commission_rate': 6, 'image': 'products/minecraft.jpg'}, # noqa: E501
            {'title': 'Jogo: Red Dead Redemption 2', 'description': 'Ação e aventura no Velho Oeste', 'price': 59.99, 'stock': 1440, 'commission_rate': 12, 'image': 'products/red_dead_redemption_2.jpg'}, # noqa: E501
            {'title': 'Jogo: FIFA 22', 'description': 'Simulação de futebol com times e jogadores reais', 'price': 54.99, 'stock':1660, 'commission_rate': 10, 'image': 'products/fifa_22.jpg'}, # noqa: E501
            {'title': 'Jogo: Grand Theft Auto V', 'description': 'Ação e aventura em um mundo aberto', 'price': 39.99, 'stock': 1630, 'commission_rate': 8, 'image': 'products/gta_v.jpg'}, # noqa: E501
            {'title': 'Jogo: The Legend of Zelda: Breath of the Wild', 'description': 'Aventura épica com elementos de RPG', 'price': 49.99, 'stock': 1020, 'commission_rate': 10, 'image': 'products/zelda_breath_of_the_wild.jpg'}, # noqa: E501
            {'title': 'Jogo: Assassin\'s Creed Valhalla', 'description': 'Ação e aventura com temática viking', 'price': 54.99, 'stock': 1640, 'commission_rate': 10, 'image': 'products/assassins_creed_valhalla.jpg'}, # noqa: E501
            {'title': 'Jogo: Call of Duty: Warzone', 'description': 'Battle royale de tiro em primeira pessoa', 'price': 0.00, 'stock': 1000, 'commission_rate': 6, 'image': 'products/call_of_duty_warzone.jpg'}, # noqa: E501
            {'title': 'Jogo: Super Mario Odyssey', 'description': 'Aventura de plataforma com o Mario', 'price': 49.99, 'stock': 750, 'commission_rate': 8, 'image': 'products/super_mario_odyssey.jpg'}, # noqa: E501
            {'title': 'Jogo: Grand Theft Auto V', 'description': 'Ação e aventura em um mundo aberto', 'price': 39.99, 'stock': 500, 'commission_rate': 8, 'image': 'products/gta_v.jpg'}, # noqa: E501
            {'title': 'Jogo: The Legend of Zelda: Breath of the Wild', 'description': 'Aventura épica com elementos de RPG', 'price': 49.99, 'stock': 20, 'commission_rate': 10, 'image': 'products/zelda_breath_of_the_wild.jpg'}, # noqa: E501
            {'title': 'Jogo: Assassin\'s Creed Valhalla', 'description': 'Ação e aventura com temática viking', 'price': 54.99, 'stock': 40, 'commission_rate': 10, 'image': 'products/assassins_creed_valhalla.jpg'}, # noqa: E501
            {'title': 'Jogo: Call of Duty: Warzone', 'description': 'Battle royale de tiro em primeira pessoa', 'price': 0.00, 'stock': 100, 'commission_rate': 6, 'image': 'products/call_of_duty_warzone.jpg'}, # noqa: E501
            {'title': 'Jogo: Super Mario Odyssey', 'description': 'Aventura de plataforma com o Mario', 'price': 49.99, 'stock': 1825, 'commission_rate': 8, 'image': 'products/super_mario_odyssey.jpg'}, # noqa: E501
            {'title': 'Jogo: Cyberpunk 2077', 'description': 'RPG de ação em um mundo aberto futurista', 'price': 59.99, 'stock': 1950, 'commission_rate': 10, 'image': 'products/cyberpunk_2077.jpg'}, # noqa: E501
            {'title': 'Jogo: The Last of Us Part II', 'description': 'Ação e aventura com elementos de survival horror', 'price': 59.99, 'stock': 1400, 'commission_rate': 12, 'image': 'products/the_last_of_us_part_ii.jpg'}, # noqa: E501
            {'title': 'Jogo: The Elder Scrolls V: Skyrim', 'description': 'RPG de ação em um mundo aberto', 'price': 39.99, 'stock': 1430, 'commission_rate': 8, 'image': 'products/skyrim.jpg'}, # noqa: E501
            {'title': 'Jogo: The Witcher 3: Wild Hunt', 'description': 'RPG de ação ambientado em um mundo aberto', 'price': 49.99, 'stock': 1250, 'commission_rate': 10, 'image': 'products/witcher_3.jpg'}, # noqa: E501
            {'title': 'Jogo: Overwatch', 'description': 'Jogo de tiro em equipe com heróis', 'price': 39.99, 'stock': 1330, 'commission_rate': 8, 'image': 'products/overwatch.jpg'}, # noqa: E501
            {'title': 'Jogo: Minecraft', 'description': 'Jogo sandbox de construção e aventura', 'price': 24.99, 'stock': 1780, 'commission_rate': 6, 'image': 'products/minecraft.jpg'}, # noqa: E501
            {'title': 'Jogo: Red Dead Redemption 2', 'description': 'Ação e aventura no Velho Oeste', 'price': 59.99, 'stock': 1540, 'commission_rate': 102, 'image': 'products/red_dead_redemption_2.jpg'}, # noqa: E501
            {'title': 'Videogame PlayStation 5', 'description': 'Console de videogame PlayStation 5 com tecnologia de última geração', 'price': 499.99, 'stock': 500, 'commission_rate': 10, 'image': 'products/playstation_5.jpg'}, # noqa: E501
            {'title': 'Videogame Xbox Series X', 'description': 'Console de videogame Xbox Series X com desempenho avançado', 'price': 499.99, 'stock': 1440, 'commission_rate': 10, 'image': 'products/xbox_series_x.jpg'}, # noqa: E501
            {'title': 'Videogame Nintendo Switch', 'description': 'Console de videogame Nintendo Switch para jogar em casa ou em trânsito', 'price': 299.99, 'stock': 600, 'commission_rate': 8, 'image': 'products/nintendo_switch.jpg'}, # noqa: E501
            {'title': 'Videogame PC Gamer', 'description': 'Computador gamer potente para jogos de alta performance', 'price': 1499.99, 'stock': 130, 'commission_rate': 12, 'image': 'products/pc_gamer.jpg'}, # noqa: E501
            {'title': 'Videogame Retro Atari Flashback', 'description': 'Console de videogame com jogos clássicos da Atari', 'price': 49.99, 'stock': 1000, 'commission_rate': 6, 'image': 'products/atari_flashback.jpg'}, # noqa: E501
            {'title': 'Placa de Vídeo NVIDIA GeForce RTX 3080', 'description': 'Placa de vídeo NVIDIA GeForce RTX 3080 com 10GB de memória GDDR6X', 'price': 1499.99, 'stock': 50, 'commission_rate': 10, 'image': 'products/nvidia_rtx_3080.jpg'}, # noqa: E501
            {'title': 'Placa de Vídeo AMD Radeon RX 6800 XT', 'description': 'Placa de vídeo AMD Radeon RX 6800 XT com 16GB de memória GDDR6', 'price': 999.99, 'stock': 40, 'commission_rate': 10, 'image': 'products/amd_rx_6800_xt.jpg'}, # noqa: E501
            {'title': 'Placa de Vídeo NVIDIA GeForce GTX 1660 Super', 'description': 'Placa de vídeo NVIDIA GeForce GTX 1660 Super com 6GB de memória GDDR6', 'price': 299.99, 'stock': 260, 'commission_rate': 8, 'image': 'products/nvidia_gtx_1660_super.jpg'}, # noqa: E501
            {'title': 'Placa de Vídeo AMD Radeon RX 5700', 'description': 'Placa de vídeo AMD Radeon RX 5700 com 8GB de memória GDDR6', 'price': 399.99, 'stock': 230, 'commission_rate': 12, 'image': 'products/amd_rx_5700.jpg'}, # noqa: E501
            {'title': 'Placa de Vídeo NVIDIA GeForce GT 1030', 'description': 'Placa de vídeo NVIDIA GeForce GT 1030 com 2GB de memória GDDR5', 'price': 99.99, 'stock': 200, 'commission_rate': 6, 'image': 'products/nvidia_gt_1030.jpg'}, # noqa: E501
            {'title': 'Placa de Vídeo NVIDIA GeForce RTX 3070', 'description': 'Placa de vídeo NVIDIA GeForce RTX 3070 com 8GB de memória GDDR6', 'price': 999.99, 'stock': 250, 'commission_rate': 10, 'image': 'products/nvidia_rtx_3070.jpg'}, # noqa: E501
            {'title': 'Placa de Vídeo AMD Radeon RX 6900 XT', 'description': 'Placa de vídeo AMD Radeon RX 6900 XT com 16GB de memória GDDR6', 'price': 1499.99, 'stock': 240, 'commission_rate': 10, 'image': 'products/amd_rx_6900_xt.jpg'}, # noqa: E501
            {'title': 'Placa de Vídeo NVIDIA GeForce GTX 1650', 'description': 'Placa de vídeo NVIDIA GeForce GTX 1650 com 4GB de memória GDDR5', 'price': 199.99, 'stock': 260, 'commission_rate': 8, 'image': 'products/nvidia_gtx_1650.jpg'}, # noqa: E501
            {'title': 'Placa de Vídeo AMD Radeon RX 5600 XT', 'description': 'Placa de vídeo AMD Radeon RX 5600 XT com 6GB de memória GDDR6', 'price': 349.99, 'stock': 330, 'commission_rate': 12, 'image': 'products/amd_rx_5600_xt.jpg'}, # noqa: E501
            {'title': 'Placa de Vídeo NVIDIA GeForce GTX 1050 Ti', 'description': 'Placa de vídeo NVIDIA GeForce GTX 1050 Ti com 4GB de memória GDDR5', 'price': 149.99, 'stock': 400, 'commission_rate': 6, 'image': 'products/nvidia_gtx_1050_ti.jpg'}, # noqa: E501
            {'title': 'Cadeira Gamer Alpha Series', 'description': 'Cadeira gamer ergonômica com estofamento em couro sintético', 'price': 249.99, 'stock': 750, 'commission_rate': 10, 'image': 'products/cadeira_gamer_alpha.jpg'}, # noqa: E501
            {'title': 'Cadeira Gamer Beta Series', 'description': 'Cadeira gamer com encosto ajustável e suporte para cabeça', 'price': 199.99, 'stock': 400, 'commission_rate': 8, 'image': 'products/cadeira_gamer_beta.jpg'}, # noqa: E501
            {'title': 'Cadeira Gamer Gamma Series', 'description': 'Cadeira gamer com apoio para os braços e inclinação ajustável', 'price': 179.99, 'stock': 360, 'commission_rate': 8, 'image': 'products/cadeira_gamer_gamma.jpg'}, # noqa: E501
            {'title': 'Cadeira Gamer Delta Series', 'description': 'Cadeira gamer com design esportivo e almofadas lombares', 'price': 299.99, 'stock': 430, 'commission_rate': 12, 'image': 'products/cadeira_gamer_delta.jpg'}, # noqa: E501
            {'title': 'Cadeira Gamer Epsilon Series', 'description': 'Cadeira gamer com suporte para até 150kg e rodinhas silenciosas', 'price': 349.99, 'stock': 620, 'commission_rate': 12, 'image': 'products/cadeira_gamer_epsilon.jpg'}, # noqa: E501
            {'title': 'Jogo: Metal Gear Solid V: The Phantom Pain', 'description': 'Ação furtiva em mundo aberto com enredo complexo', 'price': 19.99, 'stock': 1550, 'commission_rate': 6, 'image': 'products/metal_gear_solid_v.jpg'}, # noqa: E501
            {'title': 'Jogo: BioShock Infinite', 'description': 'Aventura FPS com uma história cativante', 'price': 29.99, 'stock': 1640, 'commission_rate': 6, 'image': 'products/bioshock_infinite.jpg'}, # noqa: E501
            {'title': 'Jogo: The Elder Scrolls V: Skyrim', 'description': 'RPG épico em mundo aberto com infinitas possibilidades', 'price': 39.99, 'stock': 1700, 'commission_rate': 8, 'image': 'products/skyrim.jpg'}, # noqa: E501
            {'title': 'Jogo: Portal 2', 'description': 'Puzzle de ação em primeira pessoa com uma história envolvente', 'price': 14.99, 'stock': 1600, 'commission_rate': 6, 'image': 'products/portal_2.jpg'}, # noqa: E501
            {'title': 'Jogo: Halo: The Master Chief Collection', 'description': 'Coletânea de jogos de tiro em primeira pessoa com o icônico Master Chief', 'price': 39.99, 'stock': 50, 'commission_rate': 8, 'image': 'products/halo_master_chief_collection.jpg'}, # noqa: E501
            {'title': 'Jogo: Diablo III', 'description': 'RPG de ação com loot e combate intenso', 'price': 19.99, 'stock': 3370, 'commission_rate': 6, 'image': 'products/diablo_iii.jpg'}, # noqa: E501
            {'title': 'Jogo: The Sims 4: Seasons', 'description': 'Expansão do The Sims 4 com estações do ano e eventos temáticos', 'price': 19.99, 'stock': 1400, 'commission_rate': 6, 'image': 'products/the_sims_4_seasons.jpg'}, # noqa: E501
            {'title': 'Jogo: Resident Evil 7: Biohazard', 'description': 'Survival horror com atmosfera tensa e sustos intensos', 'price': 29.99, 'stock': 1600, 'commission_rate': 6, 'image': 'products/resident_evil_7.jpg'}, # noqa: E501
            {'title': 'Jogo: Fallout 4', 'description': 'RPG de mundo aberto pós-apocalíptico com escolhas morais', 'price': 24.99, 'stock': 1800, 'commission_rate': 6, 'image': 'products/fallout_4.jpg'}, # noqa: E501
            {'title': 'Jogo: Overwatch', 'description': 'Jogo de tiro em equipe com heróis diversos', 'price': 39.99, 'stock': 50, 'commission_rate': 8, 'image': 'products/overwatch.jpg'}, # noqa: E501
            {'title': 'Jogo: Doom Eternal', 'description': 'Ação frenética em primeira pessoa contra hordas de demônios', 'price': 39.99, 'stock': 1260, 'commission_rate': 8, 'image': 'products/doom_eternal.jpg'}, # noqa: E501
            {'title': 'Jogo: Assassin\'s Creed Origins', 'description': 'Aventura histórica no Antigo Egito', 'price': 49.99, 'stock': 1840, 'commission_rate': 8, 'image': 'products/assassins_creed_origins.jpg'}, # noqa: E501
            {'title': 'Jogo: Crash Bandicoot 4: It\'s About Time', 'description': 'Aventura de plataforma com o adorável Crash Bandicoot', 'price': 59.99, 'stock': 30, 'commission_rate': 8, 'image': 'products/crash_bandicoot_4.jpg'}, # noqa: E501
            {'title': 'Jogo: Splatoon 2', 'description': 'Jogo de tiro em terceira pessoa com tinta colorida', 'price': 49.99, 'stock': 250, 'commission_rate': 8, 'image': 'products/splatoon_2.jpg'}, # noqa: E501
            {'title': 'Jogo: Genshin Impact', 'description': 'RPG de ação em mundo aberto com belos visuais', 'price': 0.00, 'stock': 300, 'commission_rate': 6, 'image': 'products/genshin_impact.jpg'}, # noqa: E501
            {'title': 'Jogo: The Sims 4', 'description': 'Simulador de vida com criação de personagens e construção de casas', 'price': 39.99, 'stock': 800, 'commission_rate': 8, 'image': 'products/the_sims_4.jpg'}, # noqa: E501
            {'title': 'Jogo: World of Warcraft: Shadowlands', 'description': 'MMORPG de fantasia com batalhas épicas', 'price': 59.99, 'stock': 280, 'commission_rate': 8, 'image': 'products/world_of_warcraft_shadowlands.jpg'}, # noqa: E501
            {'title': 'Jogo: Persona 5 Royal', 'description': 'RPG com elementos de simulação social e estilo único', 'price': 49.99, 'stock': 400, 'commission_rate': 8, 'image': 'products/persona_5_royal.jpg'}, # noqa: E501
            {'title': 'Jogo: Uncharted 4: A Thief\'s End', 'description': 'Ação e aventura com o intrépido Nathan Drake', 'price': 29.99, 'stock': 600, 'commission_rate': 6, 'image': 'products/uncharted_4.jpg'}, # noqa: E501
            {'title': 'Jogo: League of Legends', 'description': 'MOBA competitivo com estratégia em equipe', 'price': 0.00, 'stock': 3000, 'commission_rate': 6, 'image': 'products/league_of_legends.jpg'}, # noqa: E501
            {'title': 'Jogo: The Legend of Zelda: Breath of the Wild', 'description': 'Aventura épica com elementos de RPG', 'price': 59.99, 'stock': 1500, 'commission_rate': 10, 'image': 'products/zelda_breath_of_the_wild.jpg'}, # noqa: E501
            {'title': 'Jogo: Horizon Zero Dawn', 'description': 'Ação e aventura em um mundo pós-apocalíptico', 'price': 39.99, 'stock': 1600, 'commission_rate': 8, 'image': 'products/horizon_zero_dawn.jpg'}, # noqa: E501
            {'title': 'Jogo: Minecraft', 'description': 'Jogo sandbox de construção e aventura', 'price': 29.99, 'stock': 1280, 'commission_rate': 6, 'image': 'products/minecraft.jpg'}, # noqa: E501
            {'title': 'Jogo: Fortnite', 'description': 'Battle royale com construção e competição online', 'price': 0.00, 'stock': 1500, 'commission_rate': 6, 'image': 'products/fortnite.jpg'}, # noqa: E501
            {'title': 'Jogo: God of War', 'description': 'Ação e aventura mitológica com combates intensos', 'price': 49.99, 'stock': 1400, 'commission_rate': 8, 'image': 'products/god_of_war.jpg'}, # noqa: E501
            {'title': 'Jogo: Pokémon Sword', 'description': 'RPG de aventura com captura e batalhas de Pokémon', 'price': 49.99, 'stock': 1300, 'commission_rate': 8, 'image': 'products/pokemon_sword.jpg'}, # noqa: E501
            {'title': 'Jogo: Resident Evil Village', 'description': 'Survival horror com terror e mistério', 'price': 59.99, 'stock': 1220, 'commission_rate': 8, 'image': 'products/resident_evil_village.jpg'}, # noqa: E501
            {'title': 'Jogo: Just Dance 2022', 'description': 'Jogo de dança com músicas populares e coreografias', 'price': 39.99, 'stock': 1350, 'commission_rate': 8, 'image': 'products/just_dance_2022.jpg'}, # noqa: E501
            {'title': 'Caneta Pilot Preta', 'description': 'Caneta esferográfica preta da marca Pilot', 'price': 2.00, 'stock': 20000, 'commission_rate': 5, 'image': 'products/pilot_black.jpg'}, # noqa: E501
            {'title': 'Caneta Faber-Castell Colorida', 'description': 'Conjunto de canetas coloridas da marca Faber-Castell', 'price': 10.99, 'stock': 10000, 'commission_rate': 8, 'image': 'products/faber_castell_color.jpg'}, # noqa: E501
            {'title': 'Caneta Stabilo Marca-texto', 'description': 'Caneta marca-texto da marca Stabilo para destacar textos', 'price': 1.99, 'stock': 25000, 'commission_rate': 5, 'image': 'products/stabilo_highlighter.jpg'}, # noqa: E501
            {'title': 'Caneta Pentel EnerGel', 'description': 'Caneta gel com secagem rápida da marca Pentel', 'price': 3.50, 'stock': 15000, 'commission_rate': 6, 'image': 'products/pentel_energel.jpg'}, # noqa: E501
            {'title': 'Caneta Staedtler Triplus Fineliner', 'description': 'Caneta fineliner de ponta fina da marca Staedtler', 'price': 1.99, 'stock': 25000, 'commission_rate': 5, 'image': 'products/staedtler_fineliner.jpg'}, # noqa: E501
            {'title': 'Caneta Sharpie Permanente', 'description': 'Caneta permanente para escrever em diversas superfícies da marca Sharpie', 'price': 2.50, 'stock': 20000, 'commission_rate': 5, 'image': 'products/sharpie_permanent.jpg'}, # noqa: E501
            {'title': 'Caneta Papermate Flair', 'description': 'Caneta de ponta porosa com cores vibrantes da marca Papermate', 'price': 1.50, 'stock': 30000, 'commission_rate': 5, 'image': 'products/papermate_flair.jpg'}, # noqa: E501
            {'title': 'Pacote de Papel Reciclado Ofício Tilibra', 'description': 'Papel reciclado na cor creme tamanho ofício (216 x 330 mm)', 'price': 12.99, 'stock': 13000, 'commission_rate': 5, 'image': 'products/reciclado_oficio.jpg'}, # noqa: E501
            {'title': 'Pacote de Papel Reciclado A4 Tilibra', 'description': 'Papel reciclado branco tamanho A4 (210 x 297 mm)', 'price': 18.99, 'stock': 15000, 'commission_rate': 5, 'image': 'products/reciclado_a4.jpg'}, # noqa: E501
            {'title': 'Pacote de Papel Reciclado Colorido Tilibra', 'description': 'Papel reciclado em diversas cores para trabalhos criativos', 'price': 22.99, 'stock': 15000, 'commission_rate': 5, 'image': 'products/reciclado_colorido.jpg'}, # noqa: E501
            {'title': 'Pacote de Papel Reciclado Kraft Tilibra', 'description': 'Papel reciclado marrom estilo kraft para projetos rústicos', 'price': 16.99, 'stock': 3000, 'commission_rate': 5, 'image': 'products/reciclado_kraft.jpg'}, # noqa: E501
            {'title': 'Cabo USB Tipo A para Tipo C', 'description': 'Cabo USB com conector Tipo A e Tipo C para transferência de dados e carregamento rápido', 'price': 9.99, 'stock': 5000, 'commission_rate': 5, 'image': 'products/usb_tipoa_tipoC.jpg'}, # noqa: E501
            {'title': 'Cabo USB Tipo C para Tipo C', 'description': 'Cabo USB com conector Tipo C para Tipo C para transferência de dados e carregamento rápido', 'price': 12.99, 'stock': 4000, 'commission_rate': 5, 'image': 'products/usb_tipoC_tipoC.jpg'}, # noqa: E501
            {'title': 'Cabo USB Tipo A para Micro USB', 'description': 'Cabo USB com conector Tipo A e Micro USB para transferência de dados e carregamento', 'price': 7.99, 'stock': 6000, 'commission_rate': 5, 'image': 'products/usb_tipoA_microUSB.jpg'}, # noqa: E501
            {'title': 'Cabo USB Tipo C para Lightning', 'description': 'Cabo USB com conector Tipo C e Lightning para transferência de dados e carregamento de dispositivos Apple', 'price': 14.99, 'stock': 13000, 'commission_rate': 5, 'image': 'products/usb_tipoC_lightning.jpg'}, # noqa: E501
            {'title': 'Cabo USB Tipo A para USB Mini', 'description': 'Cabo USB com conector Tipo A e USB Mini para transferência de dados e carregamento de dispositivos antigos', 'price': 6.99, 'stock': 7000, 'commission_rate': 5, 'image': 'products/usb_tipoA_usbMini.jpg'}, # noqa: E501
            {'title': 'Cabo de Rede Cat 6', 'description': 'Cabo de rede Cat 6 para conexões Ethernet de alta velocidade', 'price': 12.99, 'stock': 5000, 'commission_rate': 5, 'image': 'products/cabo_rede_cat6.jpg'}, # noqa: E501
            {'title': 'Cabo de Rede Cat 6a', 'description': 'Cabo de rede Cat 6a para conexões Ethernet de alta velocidade e maior desempenho', 'price': 14.99, 'stock': 4000, 'commission_rate': 5, 'image': 'products/cabo_rede_cat6a.jpg'}, # noqa: E501
            {'title': 'Cabo de Rede Cat 7', 'description': 'Cabo de rede Cat 7 para conexões Ethernet de alta velocidade e menor interferência', 'price': 16.99, 'stock': 3000, 'commission_rate': 5, 'image': 'products/cabo_rede_cat7.jpg'}, # noqa: E501
            {'title': 'Cabo de Rede Cat 5e', 'description': 'Cabo de rede Cat 5e para conexões Ethernet de velocidade média', 'price': 9.99, 'stock': 6000, 'commission_rate': 5, 'image': 'products/cabo_rede_cat5e.jpg'}, # noqa: E501
            {'title': 'Cabo de Rede Cat 8', 'description': 'Cabo de rede Cat 8 para conexões Ethernet de alta velocidade e máxima largura de banda', 'price': 18.99, 'stock': 2000, 'commission_rate': 5, 'image': 'products/cabo_rede_cat8.jpg'}, # noqa: E501
            {'title': 'Cabo HDMI 2.0', 'description': 'Cabo HDMI versão 2.0 para transmissão de áudio e vídeo em alta definição', 'price': 14.99, 'stock': 5000, 'commission_rate': 5, 'image': 'products/hdmi_2.0.jpg'}, # noqa: E501
            {'title': 'Cabo HDMI 2.1', 'description': 'Cabo HDMI versão 2.1 para transmissão de áudio e vídeo em alta definição e suporte a recursos avançados', 'price': 19.99, 'stock': 4000, 'commission_rate': 5, 'image': 'products/hdmi_2.1.jpg'}, # noqa: E501
            {'title': 'Cabo HDMI 4K', 'description': 'Cabo HDMI para transmissão de áudio e vídeo em resolução 4K', 'price': 12.99, 'stock': 6000, 'commission_rate': 5, 'image': 'products/hdmi_4k.jpg'}, # noqa: E501
            {'title': 'Cabo HDMI Ultra HD', 'description': 'Cabo HDMI para transmissão de áudio e vídeo em resolução Ultra HD (UHD)', 'price': 16.99, 'stock': 3000, 'commission_rate': 5, 'image': 'products/hdmi_ultra_hd.jpg'}, # noqa: E501
            {'title': 'Cabo HDMI Premium', 'description': 'Cabo HDMI de alta qualidade para transmissão de áudio e vídeo sem perda de sinal', 'price': 24.99, 'stock': 2000, 'commission_rate': 5, 'image': 'products/hdmi_premium.jpg'}, # noqa: E501
            {'title': 'Pasta Arquivo com Elástico Office', 'description': 'Pasta arquivo com elástico para organizar documentos e papéis', 'price': 8.99, 'stock': 5000, 'commission_rate': 5, 'image': 'products/pasta_arquivo_elastico.jpg'}, # noqa: E501
            {'title': 'Pasta Suspensa Office', 'description': 'Pasta suspensa para armazenamento de documentos com etiquetas identificadoras', 'price': 8.99, 'stock': 4000, 'commission_rate': 5, 'image': 'products/pasta_suspensa.jpg'}, # noqa: E501
            {'title': 'Pasta Catálogo Office', 'description': 'Pasta catálogo com bolsas plásticas para organização de catálogos e folhetos', 'price': 15.99, 'stock': 3000, 'commission_rate': 5, 'image': 'products/pasta_catalogo.jpg'}, # noqa: E501
            {'title': 'Pasta Lombo Largo Office', 'description': 'Pasta com lombo largo para armazenar e organizar uma grande quantidade de documentos', 'price': 14.99, 'stock': 6000, 'commission_rate': 5, 'image': 'products/pasta_lombo_largo.jpg'}, # noqa: E501
            {'title': 'Pasta Portfólio Office', 'description': 'Pasta portfólio para transportar e proteger trabalhos artísticos e projetos', 'price': 26.99, 'stock': 2000, 'commission_rate': 5, 'image': 'products/pasta_portfolio.jpg'}, # noqa: E501
            {'title': 'Microsoft 365 Family', 'description': '1 licença para até 6 usuários Assinatura 15 meses e Kaspersky Antivírus Total Security para 5 dispositivos Licença 12 meses', 'price': 126.99, 'stock': 2000, 'commission_rate': 5, 'image': 'products/default.jpg'}, # noqa: E501
            {'title': 'Microsoft 365 Personal', 'description': '1 Licença - Word, Excel, PowerPoint, Outlook + 1TB de HD Virtual - Assinatura Anual - DOWNLOAD', 'price': 96.99, 'stock': 2000, 'commission_rate': 5, 'image': 'products/default.jpg'}, # noqa: E501
]

        
        for item in items:
            try:
                if not Item.objects.filter(title=item['title']).exists():
                    Item.objects.create(
                        title=item['title'], 
                        description=item['description'],
                        price=item['price'], 
                        stock=item['stock'], 
                        commission_rate=item['commission_rate'], 
                        image=item['image']
                    )
                    self.stdout.write(self.style.SUCCESS(f'Item {item["title"]} importado com sucesso'))
                else:
                    self.stdout.write(self.style.WARNING(f'Item {item["title"]} já existe. Não foi importado.'))
            except Exception as e:
                self.stdout.write(self.style.ERROR(f'Erro ao importar o item {item["title"]}: {e}'))