# Generated by Django 4.2.2 on 2023-06-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document_date',
            field=models.DateTimeField(default='20230101'),
            preserve_default=False,
        ),
    ]
