# Generated by Django 4.2.2 on 2023-06-11 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0002_order_document_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10}$|^\\d{11}$', "O número de telefone deve estar no formato: 'XXXXXXXXXX' ou 'XXXXXXXXXXX'", 'invalido')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='document_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10}$|^\\d{11}$', "O número de telefone deve estar no formato: 'XXXXXXXXXX' ou 'XXXXXXXXXXX'", 'invalido')]),
        ),
    ]
