# Generated by Django 4.1.9 on 2023-06-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0003_alter_customer_phone_alter_order_document_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='price_at_sale',
            field=models.FloatField(blank=True),
        ),
    ]
